org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
MAPBOX_DOWNLOADS_TOKEN=pk.eyJ1IjoibGVxdXlkb24iLCJhIjoiY21vaDZldDF3MDA2czJ3cHQxdDk4Ym96ZyJ9.YrL2yQf62XlILA2Tc1Dt3w
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m